# Generated by Django 3.0.3 on 2020-03-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='justificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
