# Generated by Django 3.0.3 on 2020-03-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=40)),
                ('semestre', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='justificacion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='justificacion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='justificacion',
            name='apellidoM',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='apellidoP',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='correo',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='diaFin',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='diaInicio',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='generacion',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='justificativo',
            field=models.FileField(default=1, upload_to='justificativos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='mesFin',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='mesInicio',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='motivo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='nombre',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='rut',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificacion',
            name='asignatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asistencia.Asignatura'),
            preserve_default=False,
        ),
    ]
