# Generated by Django 3.0.3 on 2020-03-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20200302_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificacion',
            name='estado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
