# Generated by Django 3.0.3 on 2020-03-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_justificacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='correo',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='estado',
            field=models.PositiveIntegerField(),
        ),
    ]
