# Generated by Django 3.0.3 on 2020-03-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_auto_20200310_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificacion',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='justificacion',
            name='asignatura',
            field=models.ManyToManyField(to='asistencia.Asignatura'),
        ),
    ]
