# Generated by Django 3.0.3 on 2020-03-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_auto_20200311_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificacion',
            name='mesFin',
        ),
        migrations.RemoveField(
            model_name='justificacion',
            name='mesInicio',
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='diaFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='diaInicio',
            field=models.DateField(),
        ),
    ]
