# Generated by Django 3.0.3 on 2020-03-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_auto_20200311_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='correo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='semestre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
